export const balance_key = 'bilanco'
export const financial_structure_ratios_key = 'finansal-yapi-oranlari'
export const income_statement_key = 'gelir-tablosu'
export const liquid_ratios_key = 'likidite-oranlari'
export const profitability_ratios_key = 'karlilik-oranlari'
export const ratios_key = 'rasyolar'
export const revolution_speeds_key = 'devir-hizlari'
